### users list
GET http://localhost:9000/users
Accept: application/json

### users create
POST http://localhost:9000/users
Content-Type: application/json

{
  "email": "amir.aghaee73@gmail.com",
  "password": "amir24"
}

### user login
POST http://localhost:9000/login
Content-Type: application/json

{
  "email": "amir.aghaee73@gmail.com",
  "password": "amir24a"
}

### cdns list
GET http://localhost:9000/cdns
Content-Type: application/json

### cdn create
POST http://localhost:9000/cdns
Content-Type: application/json

{
  "origin": "http://127.0.0.1:8081",
  "domain": "example.com",
  "cache_ttl": 60,
  "is_active": true
}

### cdn delete
DELETE http://localhost:9000/cdns/68caa221474affe1e9d178c4
Content-Type: application/json

### snapshot
POST http://localhost:9000/snapshot
Content-Type: application/json