@baseUrl = http://localhost:9001

### USER LOGIN
# This request stores the token into the token variable
# After running this, all other API calls automatically use the token
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "amir.aghaee73@gmail.com",
  "password": "amir24"
}
> {%
    client.global.set("token", response.body.token);
%}

### USERS LIST
GET {{baseUrl}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### USER REGISTER
POST {{baseUrl}}/register
Content-Type: application/json

{
  "email": "amir.aghaees73@gmail.com",
  "password": "amir24"
}

### CDNS LIST
GET {{baseUrl}}/api/cdns
Content-Type: application/json
Authorization: Bearer {{token}}

### CDN CREATE
POST {{baseUrl}}/api/cdns
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "origin": "http://127.0.0.1:8081",
  "domain": "example.com",
  "cache_ttl": 60,
  "is_active": true
}

### CDN DELETE
DELETE {{baseUrl}}/api/cdns/68caa221474affe1e9d178c4
Content-Type: application/json
Authorization: Bearer {{token}}

### SNAPSHOT
POST {{baseUrl}}/api/snapshot
Content-Type: application/json
Authorization: Bearer {{token}}
