global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: edge
    metrics_path: /metrics
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/edge.json
        refresh_interval: 30s
